DROP SEQUENCE IF EXISTS userSeq;
DROP SEQUENCE IF EXISTS productSeq;
DROP SEQUENCE IF EXISTS orderSeq;

DROP TABLE IF EXISTS has_in_shopping_cart;
DROP TABLE IF EXISTS consists_of;
DROP TABLE IF EXISTS Component;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS order_contains;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Users;

